# Generated by Django 5.1.7 on 2026-03-19 16:06

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def build_unique_slug(model, source_value: str, pk: int) -> str:
    base_slug = slugify(source_value) or "item"
    slug = base_slug
    counter = 2

    while model.objects.filter(slug=slug).exclude(pk=pk).exists():
        slug = f"{base_slug}-{counter}"
        counter += 1

    return slug


def populate_slugs(apps, schema_editor):
    Collection = apps.get_model("core", "Collection")
    Work = apps.get_model("core", "Work")

    for collection in Collection.objects.all().iterator():
        if not collection.slug:
            collection.slug = build_unique_slug(Collection, collection.name, collection.pk)
            collection.save(update_fields=["slug"])

    for work in Work.objects.all().iterator():
        if not work.slug:
            work.slug = build_unique_slug(Work, work.title, work.pk)
            work.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="craftsmanship",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="collection",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collection",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="craftsmanship",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="craftsmanship",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="craftsmanship",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="work",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="work",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="work",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CollectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="collections/gallery/")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.collection",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="WorkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="work/gallery/")),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.work",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
