# Generated by Django 5.1.7 on 2026-03-19 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_collection_options_alter_craftsmanship_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='craftsmanship',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='craftsmanship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_craftsmanship_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='work',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('Flooring', 'Flooring'), ('Countertop', 'Countertop'), ('Stairs', 'Stairs'), ('Wall Cladding', 'Wall Cladding'), ('Pooja Room', 'Pooja Room')], max_length=120),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['status'], name='core_collec_status_2ea215_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['type'], name='core_collec_type_bb6434_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['status'], name='core_work_status_e76a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['category'], name='core_work_categor_b8862a_idx'),
        ),
    ]
